import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { openDb } from '../src/db.js';
import { vapidKeys, registerDevice, forgetDevice, devices } from '../src/push.js';

// The Alert Device lifecycle. Nothing here sends anything — a test that reaches Google's push
// service is a test that fails on a train — but everything up to the send is real, including the
// VAPID pair, which is generated by web-push itself rather than faked.

function newDb(t) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'digital-aid-alerts-'));
  const db = openDb(path.join(dir, 'test.db'));
  db.prepare(`INSERT INTO admin (id, username, password_hash, server_key, totp_secret)
              VALUES (1, 'parent', 'x', 'y', 'z')`).run();
  t.after(() => { db.close(); fs.rmSync(dir, { recursive: true, force: true }); });
  return db;
}

const sub = (endpoint) => ({ endpoint, keys: { p256dh: 'p-' + endpoint, auth: 'a-' + endpoint } });

test('VAPID keys are generated once and then reused', (t) => {
  const db = newDb(t);
  const first = vapidKeys(db);
  assert.ok(first.vapid_public && first.vapid_private);
  // Regenerating on every read would silently invalidate every subscription in the house — which
  // is exactly the failure nobody would see, because it produces no error anywhere.
  assert.deepEqual(vapidKeys(db), first);
});

test('a subscription is stored, and a malformed one is refused', (t) => {
  const db = newDb(t);
  assert.equal(registerDevice(db, sub('https://push.example/1'), 'phone'), true);
  assert.equal(registerDevice(db, { endpoint: 'https://push.example/2' }, 'no keys'), false);
  assert.equal(registerDevice(db, null, 'nothing'), false);
  assert.equal(devices(db).length, 1);
});

test('two browsers on one phone are two devices', (t) => {
  const db = newDb(t);
  registerDevice(db, sub('https://push.example/chrome'), 'chrome');
  registerDevice(db, sub('https://push.example/firefox'), 'firefox');
  assert.equal(devices(db).length, 2);
});

test('re-subscribing the same endpoint is the same device saying so again', (t) => {
  const db = newDb(t);
  registerDevice(db, sub('https://push.example/1'), 'phone');
  db.prepare('UPDATE alert_devices SET failures = 4').run();
  registerDevice(db, sub('https://push.example/1'), 'phone');
  assert.equal(devices(db).length, 1);
  // A device that has come back is not a device that has been failing.
  assert.equal(devices(db)[0].failures, 0);
});

test('forgetting a device stops it being a target', (t) => {
  const db = newDb(t);
  registerDevice(db, sub('https://push.example/1'), 'phone');
  assert.equal(forgetDevice(db, 'https://push.example/1'), 1);
  assert.equal(devices(db).length, 0);
  assert.equal(forgetDevice(db, 'https://push.example/gone'), 0);
});
