using DigitalAid.Client.Core;

namespace Client.Core.Tests;

public class GrantCodeTests
{
    private const string Seed = "0f1e2d3c4b5a69788796a5b4c3d2e1f00f1e2d3c4b5a69788796a5b4c3d2e1f0";

    private static DateTimeOffset At(long step) => DateTimeOffset.FromUnixTimeSeconds(step * GrantCode.StepSeconds);

    /// <summary>
    /// The cross-implementation contract. These numbers were generated by <c>server/src/grant-code.js</c>
    /// and are asserted identically by <c>server/test/grant-code.test.js</c> and the browser
    /// implementation in <c>public/family-code.js</c>.
    ///
    /// Three implementations of one derivation is the shape that drifts silently: a mismatch does not
    /// throw anywhere, it just means the code the parent reads out is refused by the Client, with no
    /// error to read at either end. Change the derivation and all four move together, or none do.
    /// </summary>
    public static TheoryData<string, int, long, string> Vectors => new()
    {
        { "0000000000000000000000000000000000000000000000000000000000000000", 1, 0L, "988480001" },
        { "0000000000000000000000000000000000000000000000000000000000000000", 15, 29000000L, "367888015" },
        { "0000000000000000000000000000000000000000000000000000000000000000", 999, 29000001L, "818087999" },
        { "0000000000000000000000000000000000000000000000000000000000000000", 5, 1L, "309564005" },
        { "0000000000000000000000000000000000000000000000000000000000000000", 120, 999999999L, "167821120" },
        { "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 1, 0L, "835311001" },
        { "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 15, 29000000L, "420842015" },
        { "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 999, 29000001L, "806104999" },
        { "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 5, 1L, "511501005" },
        { "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 120, 999999999L, "176081120" },
        { Seed, 1, 0L, "329746001" },
        { Seed, 15, 29000000L, "712959015" },
        { Seed, 999, 29000001L, "095873999" },
        { Seed, 5, 1L, "841609005" },
        { Seed, 120, 999999999L, "392668120" },
    };

    [Theory]
    [MemberData(nameof(Vectors))]
    public void Matches_the_shared_vectors(string seed, int minutes, long step, string expected)
    {
        Assert.Equal(expected, GrantCode.Build(seed, minutes, At(step)));
        Assert.True(GrantCode.Verify(expected, seed, At(step)));
    }

    [Theory]
    [MemberData(nameof(Vectors))]
    public void Every_code_is_nine_digits(string seed, int minutes, long step, string expected)
    {
        Assert.Equal(9, GrantCode.Build(seed, minutes, At(step)).Length);
        Assert.Equal(9, expected.Length);
    }

    /// <summary>The padding is written, not signed. This is the invariant that let ADR-0014 ship
    /// without updating a single Client first: the six derived digits are untouched, so the
    /// unpadded form a server used to mint still verifies, and the padded form a new server mints
    /// verifies on a Client that predates the change.</summary>
    [Theory]
    [MemberData(nameof(Vectors))]
    public void Padding_is_written_but_not_signed(string seed, int minutes, long step, string expected)
    {
        var unpadded = expected[..6] + minutes;
        Assert.True(GrantCode.Verify(unpadded, seed, At(step)));
        Assert.True(GrantCode.TryParse(expected, out var digits, out var parsed));
        Assert.Equal(expected[..6], digits);
        Assert.Equal(minutes, parsed);
    }

    [Theory]
    [MemberData(nameof(Vectors))]
    public void A_code_written_in_threes_verifies(string seed, int minutes, long step, string expected)
    {
        var written = GrantCode.Format(expected);
        Assert.Equal($"{expected[..3]}-{expected[3..6]}-{expected[6..]}", written);
        Assert.True(GrantCode.Verify(written, seed, At(step)));
        // The dashes must not survive into the minutes: they are a way of showing the code, and a
        // Grant of 015 minutes is a Grant of 15.
        Assert.True(GrantCode.TryParse(written, out _, out var parsed));
        Assert.Equal(minutes, parsed);
    }

    // --- Format -----------------------------------------------------------------

    [Theory]
    [InlineData("1234561", "123456", 1)]
    [InlineData("12345615", "123456", 15)]
    [InlineData("123456999", "123456", 999)]
    [InlineData(" 12345615 ", "123456", 15)]
    [InlineData("123456015", "123456", 15)]      // the padded form
    [InlineData("123-456-015", "123456", 15)]    // written in threes (ADR-0014)
    [InlineData("123 456 015", "123456", 15)]    // spaces, as a phone keyboard offers
    [InlineData("123\u2013456\u2013015", "123456", 15)] // en dashes, as a phone autocorrects them
    public void Parses_six_digits_then_minutes(string input, string digits, int minutes)
    {
        Assert.True(GrantCode.TryParse(input, out var d, out var m));
        Assert.Equal(digits, d);
        Assert.Equal(minutes, m);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("123456")]      // bare six digits — that is an Admin Code, not an Extra Time Code
    [InlineData("1234567890")]  // too long for 3 digits of minutes
    [InlineData("1234560")]     // zero minutes
    [InlineData("12345a15")]     // a stray letter is a typo, never stripped into a different code
    [InlineData("123-456-0a5")]
    public void Rejects_malformed_input(string? input) =>
        Assert.False(GrantCode.TryParse(input, out _, out _));

    // --- What the scheme is for (ADR-0006) ---------------------------------------

    /// <summary>The point of the whole change: the minutes are signed, not merely appended, so the
    /// old trick of editing the trailing number cannot mint time.</summary>
    [Fact]
    public void Editing_the_minutes_invalidates_the_code()
    {
        var now = At(29_000_000);
        var code = GrantCode.Build(Seed, 15, now);

        Assert.True(GrantCode.Verify(code, Seed, now));
        Assert.False(GrantCode.Verify(code[..6] + "90", Seed, now));
        Assert.False(GrantCode.Verify(code[..6] + "1", Seed, now));
    }

    /// <summary>Extra Time Codes for different lengths share nothing, so a kid holding several of them
    /// has no pattern to extrapolate from — and none of them is an Admin Code.</summary>
    [Fact]
    public void Different_minutes_give_unrelated_codes()
    {
        var now = At(29_000_000);
        var codes = new[] { 5, 10, 15, 20, 30 }.Select(m => GrantCode.Build(Seed, m, now)[..6]).ToArray();
        Assert.Equal(codes.Length, codes.Distinct().Count());
    }

    [Fact]
    public void A_different_seed_rejects_the_code()
    {
        var now = At(29_000_000);
        var code = GrantCode.Build(Seed, 15, now);
        Assert.False(GrantCode.Verify(code, "b".PadLeft(64, 'b'), now));
    }

    /// <summary>No seed: a Client that has paired but not yet heard a hello, or one that lost its
    /// state. It must refuse rather than throw on the malformed key (ADR-0007).</summary>
    [Fact]
    public void No_seed_rejects_everything()
    {
        var now = At(29_000_000);
        Assert.False(GrantCode.Verify("12345615", "", now));
        Assert.False(GrantCode.Verify(null, "", now));
    }

    // --- The window --------------------------------------------------------------

    [Fact]
    public void Accepts_the_neighbouring_steps_but_not_beyond()
    {
        var code = GrantCode.Build(Seed, 15, At(29_000_000));

        Assert.True(GrantCode.Verify(code, Seed, At(29_000_000)));
        Assert.True(GrantCode.Verify(code, Seed, At(29_000_001)));   // Client's clock a minute behind
        Assert.True(GrantCode.Verify(code, Seed, At(28_999_999)));   // or a minute ahead
        Assert.False(GrantCode.Verify(code, Seed, At(29_000_002)));
        Assert.False(GrantCode.Verify(code, Seed, At(28_999_998)));
    }

    /// <summary>A minute of validity is the whole point of a 60-second step over TOTP's 30 — the
    /// window has to survive a read-out and a mistyped retry.</summary>
    [Fact]
    public void A_code_stays_valid_for_at_least_two_minutes_of_wall_clock()
    {
        var issued = DateTimeOffset.FromUnixTimeSeconds(29_000_000L * 60);
        var code = GrantCode.Build(Seed, 15, issued);

        Assert.True(GrantCode.Verify(code, Seed, issued.AddSeconds(115)));
        Assert.False(GrantCode.Verify(code, Seed, issued.AddSeconds(130)));
    }
}
